### ISSUE TITLE
Feature request - anonymous lists

### ISSUE THREAD

**Issue by marwl** [nanawel/our-shopping-list#1]
Hello I tried out the shopping list and it's great and simple.
Instead of a user concept how about a simple approach with sort of one time lists.
So what I'm trying to say is what are your thoughts about not showing all lists at the front and when you create a list you have the possibility to share the list.

**Comment by nanawel** [comment]
Hi @marwl, and thanks :)

Yes that would be an option, but I'm afraid this would be too limited for most usages. For example you might want to just "share" a list with... yourself, but on another device (my main use case).

I'm still thinking on a way to be able to create lists without any user account or sending mails (2 things I want to avoid to keep this app simple to use and install), then be able to share it in some way: via QR code, special URL, etc.

I did not give up on this, but I'm lacking time at the moment so I keep on thinking about it and if I find a satisfying solution I'll give it a shot.

**Comment by nanawel** [comment]
Version 2 brings the support of "boards" that should allow a more flexible way to define lists and chare them.
Closing.
