### ISSUE TITLE
List all boards

### ISSUE THREAD

**Issue by mccarthyryanc** [nanawel/our-shopping-list#12]
Would it be possible to list all the current boards on main page?

BTW, I really love this app! It does one thing and it does it really well! :clap:

**Comment by nanawel** [comment]
Hi @mccarthyryanc 

Glad you like it :hugs: 
Yes I'll see what I can do about that. A new environment variable will probably be used to toggle this display on or off.
I'm quite busy these days but I keep this feature in mind. Thanks!

**Comment by DanZirnhelt** [comment]
I agree, this is an great simplistic app that my wife and I are using. It has been great!  Being able to see all the boards would be amazing!

**Comment by nanawel** [comment]
This is a little off-topic but as I personally don't use multi-board with my wife, could you tell me what are your usages of such a feature for you? (it's only to better understand how my app is used, no tracking whatsoever so, you know... :wink: )

**Comment by DanZirnhelt** [comment]
We have actually been using the single board which has worked great. The multi board would just allow us to split off to have our own lists in our own space. My wife makes lists for virtually everything so we have a bunch of lists between the both of us all on the left navigation. Multi board would still allow us to easily view eaachothers but from. What I can tell you have to remember the board name. So being able to see and click on a board from the home screen would help.

**Comment by nanawel** [comment]
I see! Thanks for your feedback!

**Comment by nanawel** [comment]
Hi @mccarthyryanc @DanZirnhelt 
You should check out https://dev.osl.lanterne-rouge.info/ and tell me if it works for you. I should release this version soon.
Of course it's instance-wide toggleable with a new config key: `VUE_APP_LIST_ALL_BOARDS_ENABLED` (default to off)

**Comment by mccarthyryanc** [comment]
This looks perfect! Strong work, thanks are adding the feature!

**Comment by nanawel** [comment]
Feature released in 2.6.0 via b644b2556852e45e11b37d54cce8d272c742cb25

**Comment by nickvk** [comment]
Hi! I have just installed a clean version of this tool on my server via Docker Compose. I wanted to also use this feature by enabling "VUE_APP_LIST_ALL_BOARDS_ENABLED" with value "1". But when running the tool, inside the configuration this feature has the value "0" and I don't see a list of all created boards. Am I doing something wrong?

**Comment by nanawel** [comment]
Hi @nickvk 

Please provide your `docker-compose.yml` and the associated `.env` if any.
The new name of the variable is `VITE_APP_LIST_ALL_BOARDS_ENABLED` but that should not be your problem since there's a compatibility layer that allows to use the old name too.
Make sure you also have `VITE_APP_SINGLEBOARD_MODE=0` (or not defined, since it's the default value).

**Comment by nickvk** [comment]
I have the following docker-compose file:
services:
  app:
    image: ourshoppinglist/our-shopping-list:latest
    restart: always
    ports:
      - '7912:8080'
    networks:
      - shoppinglist_network
    environment:
      # Default values below (See README for more)
      VITE_APP_I18N_LOCALE: nl
      VITE_APP_I18N_FALLBACK_LOCALE: en
      VITE_APP_I18N_FORCE_LOCALE: 0
      VITE_APP_SINGLEBOARD_MODE: 0
      VITE_APP_LIST_ALL_BOARDS_ENABLED: 1
      VITE_APP_HIDE_FORCE_REFRESH_HINT: 1
    depends_on:
      - mongodb

**Comment by nanawel** [comment]
Everything seems to be fine. 🤔 
Here's the `docker-compose.yml` I'm using for https://dev.osl.lanterne-rouge.info/

```yml
services:
  app:
    image: ourshoppinglist/our-shopping-list
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    env_file:
      - .env
```

with the following `.env`:
```
VUE_APP_CLIENT_LOG_ENABLED=1
VUE_APP_CLIENT_LOG_CONSOLE_ENABLED=1
VUE_APP_CLIENT_LOG_LEVEL=debug
VUE_APP_BOARD_DELETION_ENABLED=1
VUE_APP_EDIT_ITEM_ON_CREATE=1
VUE_APP_HOME_MESSAGE='This is a development server. Its data can be deleted at any moment.'
VUE_APP_LIST_ALL_BOARDS_ENABLED=1
VUE_APP_TITLE=Our Shopping List (DEV)
VUE_APP_USE_ITEM_QUICK_SYNTAX=1
```

So `VUE_APP_LIST_ALL_BOARDS_ENABLED` is explicitly "on" and `VUE_APP_SINGLEBOARD_MODE` is not present so defaults to "on".

You may try to move your config values to a `.env` file but I doubt it would make a difference here.

**Comment by nickvk** [comment]
Hi!

Very weird, but after leaving it running for some time the settings changed to the settings I wanted. So problem is solved, but why they are solved now is a mystery haha.

Met vriendelijke groet,

Nick van Kesteren

Op wo 4 mrt 2026, om 7:23 schreef Anaël Ollier:
