### ISSUE TITLE
Allow Boards to be deleted

### ISSUE THREAD

**Issue by AkshayRao27** [nanawel/our-shopping-list#17]
V2 allows creating multiple boards, but there doesn't seem to be any straightforward way to delete existing boards once they are no longer useful.

An option, ideally in the frontend, to delete Boards would be useful. Ideally this option should ask for a confirmation before actually deleting the board.

**Comment by nanawel** [comment]
Sorry for the delay, but here's a little Xmas gift in advance: you can test this feature on https://dev.osl.lanterne-rouge.info/

If it's okay for you, I'll soon publish a 2.9.0 with it.

**Comment by nanawel** [comment]
Released in [2.9.0](https://github.com/nanawel/our-shopping-list/releases/tag/2.9.0).

**Comment by palitu** [comment]
awesome! thanks.
