### ISSUE TITLE
Feature request: Move items between lists

### ISSUE THREAD

**Issue by danparsonson** [nanawel/our-shopping-list#27]
First let me thank you so much for this lovely little application - exactly what I was looking for and it works like a charm!

I love how clean and simple the UI is, and that it doesn't try to do anything except keep lists, but there is one small quality-of-life change that I think would be useful, and that is the ability to move items between lists within a board.

The reason for this is that I like to keep a big to-do list of things that I need to do 'sometime soon', and another list of 'things to do today' which I take from the first list (and add to during the day if anything urgent comes up). Currently I'm handling that by using only one to-do list, and prefixing today's items with * so that they sort to the top, but it would be nice if I could either:

- open an individual item and choose a new list from a drop down at the bottom of the dialog, or,
- somehow select a set of items and move them all at once

Personally I don't think you need to allow moving items between boards - simplicity is a great strength of this application and there's no need to overcomplicate things.

**Comment by nanawel** [comment]
Hi, and thanks for your kind words. 😊

Yes, this is a feature I'd like to add too. The main difficulty is not the implementation but how to make it usable on the GUI without complexifying it. Interactions and gestures are deliberately limited so this needs to be carefully considered.

I'll prioritize this in the next releases.

**Comment by nanawel** [comment]
This turned out to be pretty straightforward, and the easiest solution was to add a dropdown on the edit box.

@danparsonson You can test the result here: https://dev.osl.lanterne-rouge.info

I'll push an update in a few days if no regression is found on my side.

**Comment by danparsonson** [comment]
Looks great, thank you! I've had a play around with it at your test site and I was unable to break it.

**Comment by nanawel** [comment]
Version [3.3.0](https://github.com/nanawel/our-shopping-list/releases/tag/3.3.0) has been released. Closing.
