### ISSUE TITLE
Unable to delete list

### ISSUE THREAD

**Issue by HellSpawn754** [nanawel/our-shopping-list#29]
Hi,

Thanks for this nice software !

I use the singleboard mode using the docker (3.3.0) image. When i try to delete a list i get:

DELETE LIST d63fdabd-837c-4286-9fda-9000a008b4f0 {}
[500] TypeError: list.delete is not a function

**Comment by HellSpawn754** [comment]
version: '3.2'

services:
  app:
    image: ourshoppinglist/our-shopping-list:latest
    restart: always
    ports:
      - '8102:8080'
    environment:
      # Default values below (See README for more)
      VUE_APP_I18N_LOCALE: de
      VUE_APP_I18N_FALLBACK_LOCALE: de
      VUE_APP_I18N_FORCE_LOCALE: 0
      VUE_APP_SINGLEBOARD_MODE: 1
    # You may want to use a .env file instead
    #env_file:
    #  - .env
    #volumes:
    #  - ./robots.txt:/app/robots.txt:ro   # See README
    depends_on:
      - mongodb

  mongodb:
    # *Caution*: Before 2024-06-11 the version used was mongo:4. You *cannot* upgrade directly to mongo:7.
    # Use the automated script update-mongo7.sh to upgrade your stack to mongo:5, mongo:6 then mongo:7
    # Refer to README.md for more information
    image: mongo:7
    volumes:
      - /volume2/docker/our-shopping-list/dbdata/:/data/db

volumes:
  dbdata:

**Comment by nanawel** [comment]
Hi, and thanks :)
I'll take a look asap.

**Comment by nanawel** [comment]
Fixed in [3.3.1](https://github.com/nanawel/our-shopping-list/releases/tag/3.3.1)
Thanks for your report
