### ISSUE TITLE
Feature Request: Add user authentication

### ISSUE THREAD

**Issue by sisimomo** [nanawel/our-shopping-list#3]
Hello,

I just came across your project and it is just perfect. I'm looking for a simple and intuitive interface so that any member of my family can add items to the grocery list without difficulty (otherwise they simply won't use it).

I was going to install it on my development server, but noticed that there was no authentication to access the site. Unfortunately for me it is a necessity since I intend to expose the application on the internet. And I don't want anyone (o ther than my family) to be able to see/edit my listings. (And I also don't want to manage VPN connections on all my family member phones)

Ideally, having users with shared and private lists would be ideal. But, a simple authentication to protect the site would be good enough.

If you put that in place, I could confidently use the project for my family needs.

FYI, I have a [MagicMirror²](https://magicmirror.builders/) at my house and would like to display somes of my lists on it. So I will probably create a module for [our shopping list](https://github.com/nanawel/our-shopping-list). I took a quick look at the backend code, and all the endpoints I'll need are already available.

What do you think ?

**Comment by nanawel** [comment]
Hi @sisimomo 
Thanks for your feedback. I hope this application will help you as much as it helps me on a daily basis.

I fully understand your need for authentication, but unfortunately this is voluntarily out of the scope I intend for this application. It must remain direct, simple, lightweight. And adding users, groups or whatever is clearly already too much.

You can however add an authentication layer on top of the HTTP server if you need it (htpasswd). Or you can simply go with the simplest trick: just leave it open on a secret URL and make sure you only share it with relatives. What do you think?
(be careful though: adding authentication would make the provided [PWA feature](https://support.google.com/chrome/answer/9658361) probably a bit more difficult to use from a phone).

I did not know about MagicMirror, seems interesting indeed. I'm sure OSL would have its place there. I'm looking forward to hearing from you about the extension module you plan to add.

**Comment by charlesparvin** [comment]
For secret URLs, make sure you have robots.txt set to disallow indexing at least one directory level above your install (or else you have the secret URL inside robots.txt file)

**Comment by Hellhound1** [comment]
Hey, a simple (optional) password page would be great. I appreciate users etc is out of scope and I wouldn't require that either, but a built in password page for those of us who do want to expose it would be great. 

Same as OP, I don't want to be managing vpns on families phones to access the site while they're shopping, which is kind of the point of the site!
