### ISSUE TITLE
Access control with username and password?

### ISSUE THREAD

**Issue by houdini69** [nanawel/our-shopping-list#32]
Is it possible to implement that on our shopping list? I tested access control on nginx (htpasswd) but keyboard interaction is not ideal in browser with my password manager Vaultwarden.

**Comment by nanawel** [comment]
It would be feasible but this is voluntarily left aside. For the moment I don't want to add unneeded complexity into the app.

If you want to mitigate the problem of the username/password, remember that you can add them to the URL in your bookmarks, like this for example: `https://username:password@myosl.tld`
The `username:password` part will automatically used to populate the `Authentication` header sent to the server. That way you won't have to type them when using this bookmark.

**Comment by houdini69** [comment]
This doesn't work: the browser understands the link as a search query

**Comment by houdini69** [comment]
It works if I percent-encode password...
Thanks.

**Comment by houdini69** [comment]
But I didn't the front window on my smartphone in Vanadium...
