### ISSUE TITLE
Allow changing page title

### ISSUE THREAD

**Issue by charlesparvin** [nanawel/our-shopping-list#4]
It would be nice to have a docker environment variable  to be able to change the page's title from "Our Shopping List".

It's interesting on desktop to be able to change the tab's title to find it faster but on mobile it's also used by Firefox (and doesn't seem to be editable on Android) to set the app name when installing it from the browser (and the default name is long enough to always be truncated on the home screen)

**Comment by nanawel** [comment]
:heavy_check_mark: Noted, I'll see how I can do that. Thanks

**Comment by nanawel** [comment]
Should be fixed in https://github.com/nanawel/our-shopping-list/releases/tag/2.4.0

Just declare `VUE_APP_TITLE` in the `environment` section of your `docker-compose.yml`.

Feel free to comment if you have any issue and I'll reopen this thread.

**Comment by charlesparvin** [comment]
Hey, sorry I'm a bit late to test your update !

The env var works fine to change the web page's title but the PWA still has the "Our Shopping List" default as app title (name/short name, unsure which one is used by android to choose the shortcut's name) in manifest.json, I think it would make sense for both to be the same.

**Comment by nanawel** [comment]
Ah yes, but for this it's a bit trickier as the value is hardcoded inside a JSON file (that's how PWA works).
I guess I could add a custom entrypoint in the Docker image to replace the value on startup. I'll take a look.

**Comment by nanawel** [comment]
That should now be fixed in 2.5.0.

https://github.com/nanawel/our-shopping-list/releases/tag/2.5.0
