### ISSUE TITLE
Remote access question

### ISSUE THREAD

**Issue by steveuk23** [nanawel/our-shopping-list#7]
Hi.
I like the look of this thanks.
Is it possible to remotely add and delete items from the list and also retrieve the contents of the lists but not through the Web UI ?
Sorry I'm new to Docker but I run Home assistant which gives me the ability to send mobile notifications when someone is in a area so I would like it to send the contents of this list if we were in a supermarket.
Thanks

**Comment by steveuk23** [comment]
Thanks for the reply that looks ideal.
Have you ever thought about adding voice assistants to be able to add remove through them ?

**Comment by nanawel** [comment]
I did not.
As the primary goals of this application are for it to be lightweight and straightforward, this feature seems _very_ far from them :wink:
